### PR TITLE
from meshio >=4.0.4

### PR DESCRIPTION
**Pull request by gdmcbain**
This is for #321, attempting to also work for old meshio and Gmsh too.

### CODE REVIEW

**Comment by gdmcbain** [comment]
From #302 

> Maybe we should also add to setup.py the explicit requirement of meshio>4 if that will be the case?

I think so, at least eventually, but for the moment I'll try to accommodate new & old.

**Comment by gdmcbain** [comment]
The error is upstream in pygmsh; its release is behind its master against which this passes the tests.

**Comment by gdmcbain** [comment]
Ah good, nschloe/pygmshw#313 overnight has given us pygmsh 6.0.6; this should pass now.

**Comment by gdmcbain** [comment]
> I think so, at least eventually, but for the moment I'll try to accommodate new & old.

I abandoned this; meshio >=4.0.4 is easy to install via either pip or [conda](https://anaconda.org/conda-forge/meshio).

**Comment by gdmcbain** [comment]
This does still support MSH 2.2, not least because of `docs/examples/beams.msh` used in ex21 and `docs/examples/{square,box}.msh` used in `docs/tutorials/walkthrough.rst` and `tests/test_mesh.py`.

I think the new `meshio.Mesh.cell_sets_dict` property introduced in meshio 4 is much nicer for scikit-fem; subdomains are now quite direct and boundaries also much easier.  However, meshio 4 only defines the `meshio.Mesh.cell_sets` attribute on reading Abaqus and Gmsh's MSH 4.1.  The latter is important as that's what's generated by default by Gmsh 4 and thus pygmsh as used in various examples.  Abaqus might be useful for porting examples from Calculix, but I haven't tried that yet.  I think there's still progress being made on `meshio.read`.  There is also a `meshio.Mesh.int_data_to_sets` method which I had hoped might make MSH 2.2 as directly readable as MSH 4.1, but it isn't quite yet.

**Comment by kinnala** [comment]
Looks good. Will merge after the tests run.

**Pull request merged**
