### PR TITLE
ElementLineP2

### PR DESCRIPTION
**Pull request by gdmcbain**
The `ElementLineP2` has an interior dof.

### CODE REVIEW

**Comment by gdmcbain** [comment]
_TODO:—_ Examples & tests.  

A couple of modifications are required to ex15 (can't use `I = m.interior_nodes()`) and ex16 (can't assume last dof is the terminal value).  &c.

**Comment by gdmcbain** [comment]
I've modified exx 15, 16, 23 so that they all work if `ElementLineP1` is changed to `ElementLineP2`.  

However, I haven't thought of a neat way to be able to select the element programmatically to facilitate testing without changing the style and structure of the examples.

**Comment by kinnala** [comment]
Thanks. I'd like to add some basic tests that use this new element. I'll look into it asap and review at the same time.

**Comment by kinnala** [comment]
I added nodality and convergence tests

**Pull request merged**
