### PR TITLE
Add paper draft

### PR DESCRIPTION
**Pull request by kinnala**
Try compilation using https://whedon.theoj.org/

### CODE REVIEW

**Comment by kinnala** [comment]
Ping @gdmcbain .

**Comment by gdmcbain** [comment]
Whedon works, thanks; it's a nifty system!

A couple of little things.

* [ ] inconsistent abbreviation of names of journals
* [ ] inconsistent capitalization of titles of articles

**Comment by gdmcbain** [comment]
How does the LaTeX command `\aap` work in https://joss.readthedocs.io/en/latest/submitting.html#example-paper-and-bibliography ?
```bibtex
journal = {\aap},
```

Anyway looking at recent articles I think the style is to name the journals without abbreviation.

**Comment by gdmcbain** [comment]
Is there a space in "C++ 11"?  Not on https://en.wikipedia.org/wiki/C++11 but there is on https://cplusplus.com/articles/cpp11/.  Hmm.

**Pull request merged**
