### PR TITLE
Add test for ElementLineHermite

### PR DESCRIPTION
**Pull request by ahojukka5**
Add test to make sure that exceptions are thrown when calling `gdof` with index > 3. After merging this PR, file `element_line_hermite.py` is having 100 % test coverage.

### CODE REVIEW

**Comment by ahojukka5** [comment]
Internally, `gdof` is calling `index_error` which raises `ValueError`. Is this intentional?

**Comment by kinnala** [comment]
> Internally, `gdof` is calling `index_error` which raises `ValueError`. Is this intentional?

Maybe `IndexError` would be more appropriate? 

> exception ValueError
> Raised when an operation or function receives an argument that has the right type but an inappropriate value, and the situation is not described by a more precise exception such as IndexError.

> exception IndexError
> Raised when a sequence subscript is out of range.

**Comment by kinnala** [comment]
Note: Apparently the flake8 check I added using Github Actions yesterday is not running on pull requests. I need to look what's causing it.

**Comment by kinnala** [comment]
Now it runs but there seems to be an issue with the Github Action I used: https://github.com/samuelmeuli/lint-action/issues/13

**Pull request closed without merging**
