### PR TITLE
ElementTetMini

### PR DESCRIPTION
**Pull request by gdmcbain**
This is for #371.

Basically it's copied from `ElementTriMini`.

The cofficient on the bubble remains unclear.

The element has been added to `tests/test_elements.py` but not yet `test/test_convergence.py`.

### CODE REVIEW

**Comment by gdmcbain** [comment]
The convergence test, copied from that for `ElementTriMini` fails as the element is of degree 1 + dim = 4 and so needs `get_quadrature_tet(2 * 4)` but it looks like only up to 4 is available.  (How does the test work for `ElementTriMini` work then?  Doesn't that need order 2 * (1 + dim) = 6?)

**Comment by gdmcbain** [comment]
Ah, there's reduced integration in `tests.test_convergence.ConvergenceTetP1` and its descendents.

**Comment by gdmcbain** [comment]
I think the only thing missing now is a sensible choice of coefficient for the bubble.

And maybe an example. #372

**Comment by gdmcbain** [comment]
ex32 still works with the simple replacement `ElementTetP2` -> `ElementTetMini`.

**Comment by kinnala** [comment]
Fantastic. I'll add a changelog entry. Otherwise it looks fine.

**Pull request merged**
