### PR TITLE
reinstate Mesh.meshio_type

### PR DESCRIPTION
**Pull request by gdmcbain**
As discussed in #579.

### CODE REVIEW

**Comment by gdmcbain** [comment]
```
==================================== ERRORS ====================================
_____________________ ERROR collecting skfem/mesh/mesh.py ______________________
skfem/mesh/mesh.py:405: in meshio_type
    return TYPE_MESH_MAPPING[cls]
E   KeyError: <class 'skfem.mesh.mesh.Mesh'>
=========================== short test summary info ============================
ERROR skfem/mesh/mesh.py - KeyError: <class 'skfem.mesh.mesh.Mesh'>
!!!!!!!!!!!!!!!!!!!! Interrupted: 1 error during collection !!!!!!!!!!!!!!!!!!!!
=============================== 1 error in 0.85s ===============================
```

I'm not sure what this is and can't reproduce it here with Python 3.9.0 under Ubuntu 20.04.2 LTS; `pytest -n auto tests` is clear.

**Comment by kinnala** [comment]
Strange stuff. I read that something was changed in Python 3.9 in relation to classmethods: https://bugs.python.org/issue42832

**Comment by kinnala** [comment]
Btw, this should run exactly the same setup as the test suite: https://github.com/kinnala/scikit-fem/blob/master/Makefile#L42

**Comment by gdmcbain** [comment]
Thanks, `make test_py39` looks good; unfortunately it's hard to run here because of an `SSLCertVerificationError` but that's an all too well known local problem that I labour under.

I think I'll assume that chaining decorators as in

https://github.com/kinnala/scikit-fem/blob/bac63ba847f6db6e913ff85bebccb4371c4e988c/skfem/mesh/mesh.py#L401-L403

isn't a good idea and will try to think of something else.

**Pull request closed without merging**
