### PR TITLE
no longer need to cast Path to str in Mesh.load

### PR DESCRIPTION
**Pull request by gdmcbain**
Following nschloe/meshio#546, as announced by @clbarnes in #120, it's no longer necessary to wrap a `pathlib.Path` in `str` (or take its `.name` attribute, &c.).

### CODE REVIEW

**Comment by kinnala** [comment]
is this not released or why is the test failing?

**Comment by gdmcbain** [comment]
Oh, is this working now?  It wasn't the last time I looked.  Have they fixed something upstream in meshio?

**Comment by clbarnes** [comment]
It's in meshio master, not sure if it's been released yet.

**Comment by gdmcbain** [comment]
Right, yes, it was `Mesh.save` to XDMF that was the problem.  nschloe/meshio#562 Something with the external XML library, I think.

**Pull request merged**
