### PR TITLE
Add explicit GPLv3 license to the files depending on pygmsh

### LINKED ISSUE #445: Clarify the licensing of the examples
> Part of the motivation for having those examples in that other repo rather than here was that I wasn't sure about the copyright or licensing status of the FEniCS originals; I'm not a lawyer.

I haven't been too worried about the licensing of the examples because they are separate from the main source code, depend on `skfem` proper and not the other way around.

Strictly speaking all examples that depend on, e.g., `pygmsh` are GPLv3 due to the strong copyleft feature. If you feel that we should be explicit about this, then we can simply add a comment to the docstring about the differing license.

Edit: By separate, I mean that when installing `skfem` via the main distribution channel, we distribute only the contents of the directory `skfem`:
```
(testenv) conda-shell-chrootenv:tom@tunkki:~/src/scikit-fem$ pip show scikit-fem -f | egrep '.py$'
  skfem/__init__.py
  skfem/assembly/__init__.py
  skfem/assembly/basis/__init__.py
  skfem/assembly/basis/basis.py
  skfem/assembly/basis/facet_basis.py
  skfem/assembly/basis/interior_basis.py
  skfem/assembly/dofs.py
  skfem/assembly/form/__init__.py
  skfem/assembly/form/bilinear_form.py
  skfem/assembly/form/form.py
  skfem/assembly/form/form_parameters.py
  skfem/assembly/form/functional.py
  skfem/assembly/form/linear_form.py
  skfem/element/__init__.py
  skfem/element/discrete_field.py
  skfem/element/element.py
  skfem/element/element_composite.py
  skfem/element/element_global.py
  skfem/element/element_h1.py
  skfem/element/element_hcurl.py
  skfem/element/element_hdiv.py
  skfem/element/element_hex/__init__.py
  skfem/element/element_hex/element_hex1.py
  skfem/element/element_hex/element_hex_s2.py
  skfem/element/element_line/__init__.py
  skfem/element/element_line/element_line_hermite.py
  skfem/element/element_line/element_line_mini.py
  skfem/element/element_line/element_line_p1.py
  skfem/element/element_line/element_line_p2.py
  skfem/element/element_line/element_line_pp.py
  skfem/element/element_quad/__init__.py
  skfem/element/element_quad/element_quad0.py
  skfem/element/element_quad/element_quad1.py
  skfem/element/element_quad/element_quad2.py
  skfem/element/element_quad/element_quad_bfs.py
  skfem/element/element_quad/element_quad_dg.py
  skfem/element/element_quad/element_quad_s2.py
  skfem/element/element_quad/element_quadp.py
  skfem/element/element_tet/__init__.py
  skfem/element/element_tet/element_tet_mini.py
  skfem/element/element_tet/element_tet_n0.py
  skfem/element/element_tet/element_tet_p0.py
  skfem/element/element_tet/element_tet_p1.py
  skfem/element/element_tet/element_tet_p2.py
  skfem/element/element_tet/element_tet_rt0.py
  skfem/element/element_tri/__init__.py
  skfem/element/element_tri/element_tri_argyris.py
  skfem/element/element_tri/element_tri_dg.py
  skfem/element/element_tri/element_tri_mini.py
  skfem/element/element_tri/element_tri_morley.py
  skfem/element/element_tri/element_tri_p0.py
  skfem/element/element_tri/element_tri_p1.py
  skfem/element/element_tri/element_tri_p2.py
  skfem/element/element_tri/element_tri_rt0.py
  skfem/element/element_vector_h1.py
  skfem/helpers.py
  skfem/importers/__init__.py
  skfem/importers/meshio.py
  skfem/io/__init__.py
  skfem/io/json.py
  skfem/io/meshio.py
  skfem/mapping/__init__.py
  skfem/mapping/mapping.py
  skfem/mapping/mapping_affine.py
  skfem/mapping/mapping_isoparametric.py
  skfem/mapping/mapping_mortar.py
  skfem/mesh/__init__.py
  skfem/mesh/mesh.py
  skfem/mesh/mesh2d/__init__.py
  skfem/mesh/mesh2d/mesh2d.py
  skfem/mesh/mesh2d/mesh_quad.py
  skfem/mesh/mesh2d/mesh_tri.py
  skfem/mesh/mesh3d/__init__.py
  skfem/mesh/mesh3d/mesh3d.py
  skfem/mesh/mesh3d/mesh_hex.py
  skfem/mesh/mesh3d/mesh_tet.py
  skfem/mesh/mesh_line.py
  skfem/models/__init__.py
  skfem/models/elasticity.py
  skfem/models/general.py
  skfem/models/helpers.py
  skfem/models/poisson.py
  skfem/quadrature.py
  skfem/utils.py
  skfem/version.py
  skfem/visuals/__init__.py
  skfem/visuals/matplotlib.py
```

_Originally posted by @kinnala in https://github.com/kinnala/scikit-fem/issues/439#issuecomment-665493939_

### PR DESCRIPTION
**Pull request by kinnala**
Closes #445

### CODE REVIEW

**Comment by kinnala** [comment]
@gdmcbain and @ahhuhtal I suppose you're fine with this clarification?

**Comment by gdmcbain** [comment]
Yes.  

As noted in #445, ex19 depends on scikit-sparse which is itself [two-clause BSD](https://github.com/scikit-sparse/scikit-sparse/blob/master/LICENSE.txt) as a wrapper, but the CHOLMOD that it wraps is GPL 2.1.

https://github.com/PetterS/SuiteSparse/blob/27e5a8516464a6ac40bd3fa0e5b46e51b11f4765/CHOLMOD/Cholesky/cholmod_factorize.c#L5-L10

How does that work?  I don't know.  I figure `splu` will be fine.

**Comment by gdmcbain** [comment]
Yes.  

As noted in #445, ex19 depends on scikit-sparse which is itself [two-clause BSD](https://github.com/scikit-sparse/scikit-sparse/blob/master/LICENSE.txt) as a wrapper, but the CHOLMOD that it wraps is GPL 2.1.

https://github.com/PetterS/SuiteSparse/blob/27e5a8516464a6ac40bd3fa0e5b46e51b11f4765/CHOLMOD/Cholesky/cholmod_factorize.c#L5-L10

How does that work?  I don't know.  I figure `splu` will be fine.

**Comment by kinnala** [comment]
I think scikit-sparse README explains the rationale behind the licensing in a reasonable manner:

> (The intent here is that if you, for example, buy a license to use CHOLMOD in a commercial product, then you can also go ahead and use our wrapper code with your commercial license.)

If the wrapper code was GPL-licensed and used together with a commercial license of CHOLMOD then technically distributing a commercial product based on those two would still require disclosing the source code of the wrapper code or any modifications made to it.

In Python code, dynamic linking happens only after a user runs the code in a Python interpreter on his own computer and some people have interpreted that only this is the step where the GPL-rot will spread, and hence justify different licensing of code that imports GPL-components, basically pushing the responsibility of licensing downstream. I have personally taken a different, more strict stance on this and consider anything that imports GPL 'dangerous' unless also GPL licensed.

As you can see, the whole GPL thing is a bit of a mess and that's why I try to stay out of it as much as I can.

**Pull request merged**
