### PR TITLE
DOC: correct analytical eigenmodes

### PR DESCRIPTION
**Pull request by gdmcbain**
Looking at ex19 &lsquo;Heat equation&rsquo; again, in preparation for examples on the method of characteristics #600, ex19 being the sole unsteady example to date, I noticed that the analytical formula for the eigenmodes was incorrect.

### CODE REVIEW

**Comment by gdmcbain** [comment]
The test-failures are related to pygmsh 7 in ex28, which is puzzling; I haven't used pygmsh 7 myself.  I don't think it's related to the present doc-fix.

**Comment by gdmcbain** [comment]
That looks like #669.

**Comment by gdmcbain** [comment]
Which is included in #667.  This can wait till that's merged; this isn't urgent.

**Comment by kinnala** [comment]
Can you merge master so we see that the tests run?

**Pull request merged**
