### PR TITLE
Make matplotlib an optional dependency

### PR DESCRIPTION
**Pull request by kinnala**
Starting work on #286 .

### CODE REVIEW

**Comment by kinnala** [comment]
@gdmcbain can you make a quick review at this point? Comments on the overall structure would be appreciated and if you have any ideas or alternative implementation strategies.

I'll continue with fixing rest of the examples after you think this is the right way to go forwards.

**Comment by gdmcbain** [comment]
Another thought for the further future: Thus far the visualization is based on the `skfem.Mesh` class hierarchy but it also partially implies `ElementLineP1` for `MeshLine`, `ElementTriP1` for `MeshTri`, etc., or sometimes P0, Q0, etc., I think.  Some visualization backends (Gmsh, ParaView?, ...) might support higher order elements.  Does eventually supporting higher order visualization imply anything about the structure of the `skfem.visualization` package?  Should the functions take bases rather than meshes?  (Noting that an `skfem.assembly.GlobalBasis` has a `.mesh` attribute anyway.)

**Comment by kinnala** [comment]
Fantastic suggestions, as usual. Here is a notebook I used during development.
[plotting.pdf](https://github.com/kinnala/scikit-fem/files/4008048/plotting.pdf)

I'm going to implement also the possibility of drawing through InteriorBasis since I removed the plotting of piecewise-constant and DG functions and refinterp should be used instead. I was thinking syntax like this:
```python
plot(interior_basis, solution)
```
and the call is the passed to `interior_basis.refinterp` and, e.g., `plot(m: MeshTri, ...)`.

**Comment by kinnala** [comment]
Next I start fixing the examples. It might take a while.

**Comment by kinnala** [comment]
Starting by running the Makefile under docs/examples and fixing all errors. Later fixing the docs.

**Comment by kinnala** [comment]
Starting to be ready for review. Fixes #286 .

**Comment by kinnala** [comment]
Am I missing some examples?

**Pull request merged**
