### PR TITLE
ElementQuadS2

### PR DESCRIPTION
**Pull request by gdmcbain**
This is to fulfil the two-dimensional part of #314.

### CODE REVIEW

**Comment by gdmcbain** [comment]
I've tested it locally on the two-dimensional linear elastic eigenproblem: 
[ex03_S2.py.txt](https://github.com/kinnala/scikit-fem/files/4095397/ex03_S2.py.txt).  It gives similar answers (i.e. not evincing the difficulty of #318 which seems limited to three dimensions) but takes a little while to run so I don't think ex03 should be modified to use S2 (or Q2).

**Comment by gdmcbain** [comment]
Could also drop the third of dofnames since there are no interior dofs.

**Comment by gdmcbain** [comment]
I wasn't sure about maxdeg. It's 3 for ElementQuad2; is that right, rather than 4?

**Comment by kinnala** [comment]
You could add a simple convergence test like this: https://github.com/kinnala/scikit-fem/blob/master/tests/test_convergence.py#L136

**Pull request merged**
