### PR TITLE
Mortar methods generalizations and fixes

### PR DESCRIPTION
**Pull request by kinnala**
This branch contains my work related to mortar methods.

### CODE REVIEW

**Comment by kinnala** [comment]
I'm still trying to figure out what changes are needed in order to support more general cases (such as contact problems where the boundaries do not initially match) in the future.

**Comment by gdmcbain** [comment]
Indeed... I guess just trying increasingly trickier examples might reveal what works and what else might be needed?

Is one still fairly simple example that does have a discretely nonmatching interface the insulted wire, with the wire and insulation meshed independently at different mesh-sizes so that the two sides of the interface are different polygonal approximations of the one geometric circle?

**Comment by kinnala** [comment]
Thanks for the idea of circular mortar boundary. I'll try to support it also.

**Comment by kinnala** [comment]
Now it's on a really ugly temporary state but I think the idea is now there. See the latest commit message for some spoilers. I'll continue on this next week.

**Comment by kinnala** [comment]
Fixes #215 .

**Comment by kinnala** [comment]
Instead of having explicit interface meshes, I've decided to use so-called mortar mappings that use similar interface meshes underneath. Then the syntax becomes quite nice since you only need to initialize two MortarBasis objects like this:
```python
mb = [
    MortarBasis(m, e, mapping = mortar[0], intorder=2),
    MortarBasis(M, E, mapping = mortar[1], intorder=2)
]
```
where `mortar[0]` and `mortar[1]` correspond to the different sides of the interface. Here `(m,e)` and `(M,E)` are the two meshes and their elements.

**Comment by kinnala** [comment]
This is still in very raw state. I'll continue tomorrow. First I create a new example with "real" contact problem and then I tidy up the code.

**Comment by kinnala** [comment]
kontakti

**Comment by kinnala** [comment]
mises_p2_vs_q2

von Mises stress when calculating with TriP2 and Quad2 elements.

**Comment by kinnala** [comment]
Remaining work:
- Separate MortarMapping code into a separate file and delete mesh_mortar.py
- Make creation of MortarMapping more robust to various edge cases
- Add tests

**Comment by kinnala** [comment]
Circular mortar boundary is not yet working/tested but it should be basically simple as adding a new constructor to MortarPair with slightly different definition for the projection (functions proj and param).

**Comment by kinnala** [comment]
I'm still writing ex04.rst but it will take a while because even writing down the equations for contact problems takes some meditation.

**Comment by kinnala** [comment]
Here are the docs https://kinnala.github.io/scikit-fem-docs/examples/ex04.html

**Comment by kinnala** [comment]
> I might try to reproduce the solution for the insulated wire ex17 using this

We would need to first add support for other projections than onto a predefined linear function.

In principle, it should be as easy as using different `proj` and `param` (local functions used in `MortarPair.init_2D`). In the case of insulated wire, you should probably do the projection via `arctan` of the angle of the point in polar coordinates.

In the literature, there are also ways to generalize this (such as closest point search) but I have not looked into it. I just know that it is possible.

My next goal is to create `MortarPair.init_3D` for mortaring 3D problems. It is somewhat more involved to create the integration mesh. My current plan is to use libsupermesh (https://bitbucket.org/libsupermesh/libsupermesh/src) and possibly create Python bindings for it. The idea is same: project points into d-1 dimensional domain, create integration mesh (or "supermesh", in `MortarPair.init_2D` it is simply one call to `np.unique`), generate d point quadrature rule in the integration mesh and map them into the global coordinate system to check that the orientation of the points matches over the global mortaring interface. If orientation does not match, perturb index columns in the auxiliary meshes so that they match.

**Pull request merged**
