### PR TITLE
MeshTri: Keep subdomains when refining

### PR DESCRIPTION
**Pull request by HelgeGehring**
I've made first implementation for keeping the subdomains while refinement.
But I'd guess there's some stuff missing at the moment:

- [ ]  I'd guess it can be made way faster by using numpy better.
- [ ] The facets need to be updated, too (here I don't have an idea yet how)
- [ ] I don't really know how to write tests for this

### CODE REVIEW

**Comment by kinnala** [comment]
There used to be a vectorized implementation of this before Mesh was rewritten using dataclass, I believe.

**Comment by HelgeGehring** [comment]
uijj, vectorized sounds good! was there a reason, that it didn't survive the rewriting?

**Comment by kinnala** [comment]
Me being lazy. It should be relatively easy to do for all Mesh classes at once since I believe the new elements always have a specific order. This order is defined by the hstack call here: https://github.com/kinnala/scikit-fem/blob/507a75008e168adca4848819d401bb697c30bc57/skfem/mesh/mesh_tri_1.py#L219

This defines a mapping between the old and the new elements of shape (4, nelems_old) for MeshTri and MeshQuad, (6, nelems_old) for MeshTet, etc. The refine stacking order should be added to RefDom subclasses and then this could be generalized to all Mesh types.

**Comment by kinnala** [comment]
Now I see that you do it here for the adaptive refinement. This is something else than what I was talking about (uniform refinement). This never existed and I'll check this when I have time.

**Comment by HelgeGehring** [comment]
Yes, I'm hoping do eventually get some adaptive refinement :) Thanks a lot!

**Comment by kinnala** [comment]
Idea for a test: 1. Create subdomains using Mesh.elements_satisfying(lambda x: x[0]<0.5) or similar and refine elements here and there. 2. Refine elements first and then create the subdomains. 3. Check that results match.

**Comment by kinnala** [comment]
I think looking at the order of those hstack calls you can get this new_to_old mapping directly. I'll try it out.

**Comment by kinnala** [comment]
Uniform refinement now preserves subdomains for all meshes. I'll check the adaptive refinement next.

**Comment by kinnala** [comment]
Done in #1024. I chose a slightly different approach which relies on the a priori knowledge of the order of red, blue, green elements in the new mesh.

**Pull request closed without merging**
