### PR TITLE
enable MeshLine.load

### PR DESCRIPTION
**Pull request by gdmcbain**
For #175, which in a minimal sense is just because `'line'` is missing from the `dict` in `bnd_types` in 'Mesh._parse_submeshes`, but I'll check whether anything else is required.

### CODE REVIEW

**Comment by gdmcbain** [comment]
This is enough to suppress the warning and load Physical Curves as `MeshLine.subdomains`, if present.

Fixes #175.

**Comment by gdmcbain** [comment]
Shortcoming: see #178; basically `MeshLine.p.shape[0]` and therefore `MeshLine.dim()` is whatever was in the file, typically 3.

**Comment by gdmcbain** [comment]
Fixes #178; the problem was that `MeshLine.strip_extra_coordinates` wasn't overridden and defaulted to that from `Mesh` which does nothing.

**Comment by gdmcbain** [comment]
Shortcoming: doesn't read all boundaries #175.

**Comment by gdmcbain** [comment]
This has been rewritten so that `MeshLine._build_mappings` no longer sorts `MeshLine.p`.  This required fairly extensive changes, e.g. to the
*  `__init__` method, which previously silently ignored `t`
*  `_uniform_refine`, which relied upon a subsequent call to `_build_mappings` to resort `p` and regenerate `t` from scratch

It now all works though, successfully running ex15, ex16, ex23, the various one-dimensional `tests`, and an in-house example involving multiple Gmsh `Physical Points` which become entries of `MeshLine.boundaries`.

**Comment by kinnala** [comment]
Very impressive work. Thanks a lot for these contributions.

**Comment by kinnala** [comment]
It's slightly inconvenient that building facets is now done in two places (refine and init) instead of one (_build_mappings), but we can try to workaround it later. I'm going to merge this.

**Pull request merged**
