### PR TITLE
Improvements to MappingIsoparametric caching

### PR DESCRIPTION
**Pull request by kinnala**
This simple change seems to improve Basis initialization performance quite a bit. There is also something fishy going on in Mesh._mapping that I had forgotten. I need to look further into that.

### CODE REVIEW

**Comment by kinnala** [comment]
Before
```
3.52s call     tests/test_basis.py::test_interpolator_probes[MeshHex1-e9-1-100000.0]
1.96s call     tests/test_convergence.py::ConvergenceHex2::runTest
1.84s call     tests/test_basis.py::test_trace[MeshHex1-e120-e220-False]
1.67s call     tests/test_convergence.py::FacetConvergenceHex1::runTest
1.67s call     tests/test_manufactured.py::TestExactHex2::runTest
1.04s call     tests/test_convergence.py::FacetConvergenceHexS2::runTest
1.02s call     tests/test_convergence.py::ConvergenceHex1::runTest
0.62s call     tests/test_convergence.py::ConvergenceHexS2::runTest
0.48s call     tests/test_assembly.py::IntegrateOneOverBoundaryHex2::runTest
0.45s call     tests/test_convergence.py::ConvergenceHexSplitTet1::runTest
```
After
```
1.53s call     tests/test_basis.py::test_interpolator_probes[MeshHex1-e9-1-100000.0]                      
1.41s call     tests/test_convergence.py::ConvergenceHex2::runTest                                                                                                                                                  
1.19s call     tests/test_manufactured.py::TestExactHex2::runTest  
1.10s call     tests/test_convergence.py::FacetConvergenceHex1::runTest                                   
1.04s call     tests/test_basis.py::test_trace[MeshHex1-e120-e220-False]
0.75s call     tests/test_convergence.py::ConvergenceHex1::runTest                                                                                                                                                  
0.65s call     tests/test_convergence.py::FacetConvergenceHexS2::runTest    
0.47s call     tests/test_convergence.py::ConvergenceHexS2::runTest       
0.46s call     tests/test_convergence.py::ConvergenceHexSplitTet1::runTest                                                                                                                                          
0.28s call     tests/test_manufactured.py::TestExactHexS2::runTest
```

**Comment by gdmcbain** [comment]
> There is also something fishy going on in Mesh._mapping that I had forgotten. I need to look further into that.

I had a look but nothing jumped out.  What did you think was fishy?

**Comment by kinnala** [comment]
> > There is also something fishy going on in Mesh._mapping that I had forgotten. I need to look further into that.
> 
> I had a look but nothing jumped out. What did you think was fishy?

Fixed it in this PR. That "FakeMesh" stuff in master.

**Comment by gdmcbain** [comment]
O. K., ta.

Following my huge blunder on mappings in #670, I'm going to call myself unqualified to assess this change for now.  I do hope to rectify that, but if that's holding things up, do proceed without me.

**Pull request merged**
