### PR TITLE
ElementLineP0

### PR DESCRIPTION
**Pull request by gdmcbain**
I think this is right but it needs more tests and an example.

### CODE REVIEW

**Comment by gdmcbain** [comment]
This is for #508.

**Comment by kinnala** [comment]
I think it's fine. You can add it to `TestDerivatives` and then add also a changelog entry to `README.md`.

**Comment by gdmcbain** [comment]
Wow, adding `ElementLineP0` to `elems` in `TestDerivatives` causes it to hang!

**Comment by gdmcbain** [comment]
It wasn't tripping the `ValueError` in

https://github.com/kinnala/scikit-fem/blob/e4c0a4f0e5593502a7cebf45461e176f9668ff91/tests/test_elements.py#L193-L196

e.g. `ElementLineP0.lbasis(y, 33)` returns the same as `ElementLineP0.lbasis(y, 0)`; indeed the second argument was ignored.

This was copied from other P0 elements so I've fixed this for all of them in b8d96fb.

**Comment by kinnala** [comment]
Great! Ready to merge?

**Comment by gdmcbain** [comment]
Yeah.  I'd prefer to have an example demonstrating the use of the new element but don't have an easy one in mind.

**Comment by kinnala** [comment]
Ok. Thanks.

**Pull request merged**
