### PR TITLE
0.4.0 release

### PR DESCRIPTION
**Pull request by kinnala**
Sort of "1.0.0 prerelease". Hopefully one of the last ones.

### CODE REVIEW

**Comment by gdmcbain** [comment]
Re 1.0.0: I'm thinking that there are going to be a few changes soon over at meshio nschloe/meshio#619 nschloe/meshio#568 which might affect i/o here #261 #271 #291.  I'm not sure how that affects the roadmap.  Is i/o separate enough that it won't?

**Comment by nschloe** [comment]
You can always depend on "meshio < 4", its API is stable across major versions. You can then make the switch whenever you like.

**Comment by gdmcbain** [comment]
Ta. Yes, no, I'm not so much worried about adapting here to the changes scheduled thus far for meshio 4 (transposition of keys of `cell_data`), that'll be straightforward; it's more that I'm hoping to take advantage in scikit-fem 1 of some of the other advances that might make it in like a more complete implementation of XDMF 3 or the rolling out of `cell_sets` to formats other than MED. Those will permit substantial improvements here.

**Comment by nschloe** [comment]
Ah cool. Let's make sure that we get all of this implemented in meshio then!

**Pull request merged**
