### PR TITLE
example on conjugate heat transfer in a plane channel

### PR DESCRIPTION
**Pull request by gdmcbain**
Eventually this example should be something like ex25 'Forced convection' but with a finitely thick solid wall.

This is published very prematurely (so far it's just conduction with unit properties in both phases) to demonstrate how to generate the mesh, following a discussion in scikit-fem/Lobby.

TODO:
* advection in fluid phase
* different thermal properties in each phase
* more interesting postprocessing

### CODE REVIEW

**Comment by gdmcbain** [comment]
ex28

**Comment by gdmcbain** [comment]
ex28
ex28-inlet-outlet

**Comment by gdmcbain** [comment]
ex28-inlet-outlet
ex28

**Comment by gdmcbain** [comment]
This example is ready now.

It demonstrates a ‘monolithic’ approach, which is easy in scikit-fem thanks to the facility of restricting operators to subdomains.

The other approach to conjugate heat transfer is ‘segregated’, solving each subdomain separately and then coupling along the interface #163; that might be investigated in future examples.  Segregated solution can be appealing because the thermal conductivity of the solid often far exceeds that of the fluid or it can be necessary if the phases are meshed separately.

**Comment by kinnala** [comment]
Thanks. Fantastic work. Adding it to the test suite should be quite straightforward?

**Pull request merged**
