### PR TITLE
add with-elements to cell_basis

### PR DESCRIPTION
**Pull request by HelgeGehring**
Like `with_element`, but for restricting the basis to a certain subset of elements.
Maybe there's a better name for the method to avoid confusion with `with_element` :thinking:

### CODE REVIEW

**Comment by kinnala** [comment]
I wonder if it should be called just `restrict`. There is also `Mesh.restrict` which actually removes the remaining elements.

**Comment by HelgeGehring** [comment]
Sounds good! The only downside I see would be, that there's a difference between 
```Basis(mesh.restrict, ...)```
and
```Basis(mesh, ...).restrict```
as the first one would also restrict the DOFs and the here proposed function leaves the DOFs the same.

I'd guess, if we add `restrict` to `Basis` both expressions above should behave the same?

While I think adding `restrict` to `Basis` has a value, I think the here proposed function should have a different name :thinking:
Maybe `with_elements` is just fine, as it matches the name in the constructor?

**Comment by kinnala** [comment]
I agree with your thinking.

**Comment by kinnala** [comment]
Btw, I now merged this but we usually have a changelog entry for new functionality in README.md. I also like to have some kind of simple test for each method so that it won't be forgotten as time passes and refactorings happen. If I ever rewrite Basis it is easy to forgot things such as this because the test suite runs just fine.

**Pull request merged**
