### PR TITLE
inmutable defaults for dataclasses for python 3.11

### PR DESCRIPTION
**Pull request by HelgeGehring**
Python 3.11 doesn't allow mutable defaults for dataclasses anymore. This fix solves the problem, but somehow doesn't look so nice. Also, there's no need to have multiple instances of the `doflocs` (?)

Would you have a better way to fix this?

### CODE REVIEW

**Comment by HelgeGehring** [comment]
And could you maybe add the autoformat settings you're using to the pyproject.toml? or which command are you using?

**Comment by kinnala** [comment]
Strange for Python to introduce such backwards-incompatibilities. Perhaps changing to using a dataclass for Mesh some time ago was a mistake.

**Comment by kinnala** [comment]
Oops. I use Emacs for autoindent.

**Comment by kinnala** [comment]
I think those reports are from flake8.

**Comment by HelgeGehring** [comment]
Okay, I've updated the formatting. I'd guess for now it would nice to merge it to have compatibility with Python 3.11. If there's an better way to do this we can still update it later :)

**Comment by kinnala** [comment]
Yes, I'll see that the tests are added.

**Pull request merged**
