### PR TITLE
Make expand=True the default behavior

### PR DESCRIPTION
**Pull request by kinnala**
Following the discussion from Gitter.

### CODE REVIEW

**Comment by kinnala** [comment]
A bunch of tests, examples and documentation to change.

**Comment by kinnala** [comment]
@gdmcbain this should be ready

**Comment by kinnala** [comment]
Oops, obviously not since the documentation is not updated

**Comment by gdmcbain** [comment]
Looks good! I haven't run anything, but every `diff` in `docs/examples` looks like an improvement.

**Pull request merged**
